# Generated by Django 4.0.1 on 2022-01-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_risk_start', models.IntegerField()),
                ('high_risk_end', models.IntegerField()),
                ('medium_risk_start', models.IntegerField()),
                ('medium_risk_end', models.IntegerField()),
                ('low_risk_start', models.IntegerField()),
                ('low_risk_end', models.IntegerField()),
            ],
        ),
    ]
